### ISSUE TITLE
Динамический calltracking

### ISSUE THREAD

**Issue by MakarkinPRO** [sipuni/static-calltracking#1]
Вопрос можно ли как-то реализовать? на вашей платформе, есть возможность доставать свои номера по sip протоколу на ваш sip (общий)

**Comment by ahsipuni** [comment]
Извините что не сразу ответил. Динамический коллтрекинг мы предоставляем. Ваши номера можно подключить но каждое подключение платное. Вы можеете позвонить в офис http://sipuni.com узнать все детали.
