### ISSUE TITLE
Не получилось настроить решение на сайте

### ISSUE THREAD

**Issue by roduman** [sipuni/static-calltracking#2]
Не получилось настроить решение на сайте
Подключил скрипт - < script src='/js/sipuni-calltracking.js'></script >

Прописал код как на примере:

				<script>
					// emulate window.location and document.referer for testing purposes
					wnd = {};
					wnd.location = {};
					wnd.location.href = 'http://мой сайт.com';
					wnd.document = {};
					wnd.document.referrer = 'http://google.com';

					// invoke calltracking script
					sipuniCalltracking({
						pattern: '99-99-99',
						sources: {
							'my': {'utm_my': 'name'}
						},
						phones: [
							{'src':'my',     'phone': ['333333'] },
							{'src':'organic',   'phone': ['324771'] },
						]
					}, wnd);
				</script>

Показывается параметр organic, если ввожу в адресную строку http://мой сайт.com/?utm_my=name ничего не меняется

**Comment by harabchuk** [comment]
Проверил ваш пример, сработало
Вот здесь можно потестировать https://jsfiddle.net/harabchuk/ma1a666y/

Обратите внимание, если добавляете параметры в адресной строке то эмуляцию window.location  и document.referer нужно удалить и в качестве параметра wnd подавать настоящий объект window

**Comment by roduman** [comment]
Вы писали - Обратите внимание, если добавляете параметры в адресной строке то эмуляцию window.location и document.referer нужно удалить и в качестве параметра wnd подавать настоящий объект window

Получается удаляю:

					wnd = {}; - что такое настоящий объект? Это адрес сайта? 

wnd = { http://okna-v.com };

					wnd.location = {}; - это удаляю
					wnd.location.href = ''; это удаляю
					wnd.document = {}; это удаляю
					wnd.document.referrer = ''; это удаляю

Я ничего из сказанного не понял: простите но я не программист, так визитки леплю на wordpress и на этом мои знания заканчиваются. Мне надо дать рекламщику ссылку с параметрами, чтобы если по этой ссылке кто переходил, отображался другой телефон.

Сейчас код такой:

				<div class="right-top">
					<div class="phone">тел. <span class="ct_phone">32-47-71</span></div>
				</div>
				<script>
					// emulate window.location and document.referer for testing purposes
					wnd = {};
					wnd.location = {};
					wnd.location.href = '';
					wnd.document = {};
					wnd.document.referrer = '';

					// invoke calltracking script
					sipuniCalltracking({
						pattern: '99-99-99',
						sources: {
							'zamena': {'utm_campaign': 'name'},
						},
						phones: [
							{'src':'zamena',     'phone': ['333333'] },
							{'src':'organic',   'phone': ['324771'] },
						]
					}, wnd);
				</script>

Ввожу в адресную строку http://okna-v.com/?utm_campaign=name но ничего не происходит

Мой сайт okna-v.com, может дадите более развернутый коммент что там надо сделать.

**Comment by harabchuk** [comment]
Ваш код верный, нужно только удалить  эмуляцию. Ниже правильный код, удалил wnd и в параметре внизу перед закрывающим тэгом script написал window
```
           <div class="right-top">
                <div class="phone">тел. <span class="ct_phone">32-47-71</span></div>
            </div>
            <script>
                sipuniCalltracking({
                    pattern: '99-99-99',
                    sources: {
                        'zamena': {'utm_campaign': 'name'},
                    },
                    phones: [
                        {'src':'zamena',     'phone': ['333333'] },
                        {'src':'organic',   'phone': ['324771'] },
                    ]
                }, window);
            </script>
```

**Comment by roduman** [comment]
Все удалил, оставил только - 

				<div class="right-top">
					<div class="phone">тел. <span class="ct_phone">32-47-71</span></div>
				</div>
				<script>
					sipuniCalltracking({
						pattern: '99-99-99',
						sources: {
							'zamena': {'utm_campaign': 'name'},
						},
						phones: [
							{'src':'zamena',     'phone': ['333333'] },
							{'src':'organic',   'phone': ['324771'] },
						]
					}, window);
				</script>

Вбиваю в адресную строку - http://okna-v.com/?utm_campaign=name и ничего, все по старому, почему не отображается номер 333333 не пойму

**Comment by harabchuk** [comment]
Все работает, у меня отображается номер 33333 при первом входе  http://okna-v.com/?utm_campaign=name. 

Дело в том, что когда человек хоть раз зашел с utm_campaign=name в куках запоминается этот источник и дальше при посещении других страниц или при последующем заходе этому посетителю показывается номер 3333.

Чтобы тестировать открывайте сайт каждый раз в режиме инкогнито

**Comment by roduman** [comment]
А как сделать так чтобы куки перезаписывались и действовали только в пределах одной сессии, например:

Я зашел на сайт по ссылке http://okna-v.com/?utm_campaign=name в обычном режиме со своими куками, он мне показывает номер 324771, а надо чтобы показывал 333333. Это я так понимаю происходит потому, что до этого я уже сюда заходил и для меня он менять ничего не будет.

потом я вышел, закрыл браузер, куки сбросились.

зашел по нормальной ссылке показался 324771,

опять вышел, закрыл браузер, куки сбросились.

зашел по ссылке с параметрами, показался 333333

**Comment by harabchuk** [comment]
С кукой на время сессии вы не сможете отследить звонки от людей повторно зашедших на ваш сайт из закладок. 

Например, в первый раз человек зашел по utm метке, а потом через день зашел из закладок и сделал звонок. С кукой на время сессии у вас звонок будет как при прямом заходе. А с долгоживущей кукой звонок будет с номера для utm метки. 

Но если вам точно нужна кука на время сессии это можно сделать в параметрах, для этого добавьте `cookie_ttl_days: null` . 
```
            <script>
                sipuniCalltracking({
                    cookie_ttl_days: null, 
                    pattern: '99-99-99',
                    sources: {
                        'zamena': {'utm_campaign': 'name'},
                    },
                    phones: [
                        {'src':'zamena',     'phone': ['333333'] },
                        {'src':'organic',   'phone': ['324771'] },
                    ]
                }, window);
            </script>
```

**Comment by roduman** [comment]
Мне как раз и не нужно отслеживать людей повторно заходящих на сайт, так как повторно они могут зайти например с поиска, а скрипт опять покажет им телефон 333333. По нашему замыслу это не нужно.

Осталось решить только одну задачу. Как сделать так - человек уже был на сайте, например это я, сколько бы я не заходил по ссылке http://okna-v.com/?utm_campaign=name (если это не режим инкогнито) у меня не меняется телефон, а надо чтобы менялся (т.е. мои старые куки удалялись). Это можно как-то реализовать.

**Comment by harabchuk** [comment]
У вас на сайте уже все работает как надо, в отладчике видно что кука сессионная. Я проверил в браузере, с utm  меткой номер 333 , после полного закрытия браузера и открытия и перехода на сайт без utm метки номер другой.

Возможно, у вас осталась кука старая когда она еще была долгой. Удалите куки в браузере.
И важно при проверке полностью закрывать браузер иначе сессия может сохраняться.
