### ISSUE TITLE
Множественные метки

### ISSUE THREAD

**Issue by Barmunksu** [sipuni/static-calltracking#3]
?utm_source=google&utm_medium=cpc&utm_campaign=google_adwords 
4951232323

?utm_source=google&utm_medium=cpc
49911111111

?utm_source=google
4992222222

А как вот такой запрос обработать? По отдельности в примерах все понятно, а если связанные?

**Comment by harabchuk** [comment]
Поскольку проверка источников происходит по порядку, такое можно реализовать следующим образом

```
<script>
    sipuniCalltracking({
      sources: {
        'src_campaign':{'dst': 'utm_source=google&utm_medium=cpc&utm_campaign=google_adwords'},
        'src_cpc':{'dst': 'utm_source=google&utm_medium=cpc'},
        'src_source':{'dst': 'utm_source=google'},
      },
      phones: [
        {'src':'src_campaign', 'phone':['4951232323']},
        {'src':'src_cpc', 'phone':['49911111111']},
        {'src':'src_source', 'phone':['4992222222']}
      ],
    }, window);
</script>
```

Важно лишь, чтобы параметры шли именно в таком порядке, потому что в предложенном примере проверка идет по подстроке.

**Comment by Barmunksu** [comment]
Оказалось просто, спасибо.
